### ISSUE TITLE
Approve all for superadmins for references

### ISSUE THREAD

**Issue by foozleface** [calacademy/antcat#58]

**Comment by foozleface** [comment]
Done, under "references" and then click on "latest additions"
![screen shot 2015-07-21 at 8 33 54 am](https://cloud.githubusercontent.com/assets/180338/10212313/35c85d76-67b2-11e5-897e-8591c32368f2.png)

  I'll let someone else pull the trigger. :-)

  Superadmins only.

**Comment by bpescador** [comment]
Joe,  I pulled and I think it worked fine.

Cheers, Brian

On Thu, Oct 1, 2015 at 6:31 AM, foozleface <notifications@github.com> wrote:

> Done, under "references" and then click on "latest additions"
> [image: screen shot 2015-07-21 at 8 33 54 am]
> <https://cloud.githubusercontent.com/assets/180338/10212313/35c85d76-67b2-11e5-897e-8591c32368f2.png>
>
> I'll let someone else pull the trigger. :-)
>
> Superadmins only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy/antcat/issues/58#issuecomment-144609935>.
>



-- 
Brian Fisher
Curator of Entomology and Patterson Scholar
55 Music Concourse Drive
California Academy of Sciences
San Francisco, CA 94118, USA
www.fisherlab.org
www.antweb.org
ResearchGate <https://www.researchgate.net/profile/Brian_Fisher7>
