### ISSUE TITLE
Core database needs to be available for public download.

### ISSUE THREAD

**Issue by foozleface** [calacademy/antcat#7]
This codebase isn't much use to anyone without the data....

**Comment by sblum** [comment]
meaning the data needs to be downloadable?  I don't thing the this code or the actual table structure would be easily useful to most people.  We need simple, easily understandable models for the basic classes.

**Comment by foozleface** [comment]
If someone wants to trace through this code to see how we're doing what we do, they'll want to be able to run against a database of some sort. Without a database - even an outdated one - it isn't possible to run any of this code. Most programmers run and trace code to see how things work; reading gives only a cursory understanding of the mechanics. 

  So it kind of boils down to - what is the goal of making the source available?

**Comment by sblum** [comment]
Meeting expressed obligations of the proposal (to some degree, SOP, even if it's somewhat meaningless.  Before we make DB snapshots available we should get permission from Barry.

**Comment by foozleface** [comment]
Makes sense.
