### ISSUE TITLE
Add DOI field to References

### ISSUE THREAD

**Issue by foozleface** [calacademy/antcat#85]
Unique identifier for references. "Digital object identifier". Will need add the field (it's a string) and show it when we show references.

**Comment by foozleface** [comment]
done and deployed. Need to test searching by (I think this doesn't work, yet), and seeing how much we can sync from other sources.

**Comment by bpescador** [comment]
Joe,

I added some DOI's to references and on the display side, I think it would
be best to preface the data with: "DOI:"  thus for:

Johnson, R. A. 2015. A taxonomic revision of South American species of the
seed-harvester ant genus *Pogonomyrmex* (Hymenoptera: Formicidae). Part I.
Zootaxa 4029(1):1-142 10.11646/zootaxa.4029.1.1. PDF
<http://antcat.org/documents/6491/johnson_2015_zootaxa_pogonomyrmex_of_south_america_part_i.pdf>
 142843


should be:

Johnson, R. A. 2015. A taxonomic revision of South American species of the
seed-harvester ant genus *Pogonomyrmex* (Hymenoptera: Formicidae). Part I.
Zootaxa 4029(1):1-142 DOI:10.11646/zootaxa.4029.1.1. PDF
<http://antcat.org/documents/6491/johnson_2015_zootaxa_pogonomyrmex_of_south_america_part_i.pdf>
 142843


and it should link out to:

 http://dx.doi.org/10.11646/zootaxa.4029.1.1

On Wed, Oct 14, 2015 at 5:00 PM, foozleface <notifications@github.com>
wrote:

> done and deployed. Need to test searching by (I think this doesn't work,
> yet), and seeing how much we can sync from other sources.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy/antcat/issues/85#issuecomment-148236849>.
>



-- 
Brian Fisher
Curator of Entomology and Patterson Scholar
55 Music Concourse Drive
California Academy of Sciences
San Francisco, CA 94118, USA
www.fisherlab.org
www.antweb.org
ResearchGate <https://www.researchgate.net/profile/Brian_Fisher7>
