### ISSUE TITLE
doi links

### ISSUE THREAD

**Issue by bpescador** [calacademy/antcat#92]
Joe,

I added some DOI's to references and on the display side, I think it would be best to preface the data with: "DOI:"  thus for:  

Johnson, R. A. 2015. A taxonomic revision of South American species of the seed-harvester ant genus Pogonomyrmex (Hymenoptera: Formicidae). Part I. Zootaxa 4029(1):1-142 10.11646/zootaxa.4029.1.1. PDF 142843

should be: 
Johnson, R. A. 2015. A taxonomic revision of South American species of the seed-harvester ant genus Pogonomyrmex (Hymenoptera: Formicidae). Part I. Zootaxa 4029(1):1-142 DOI:10.11646/zootaxa.4029.1.1. PDF 142843

and it should link out to:  
 http://dx.doi.org/10.11646/zootaxa.4029.1.1

**Comment by foozleface** [comment]
Makes sense.

**Comment by foozleface** [comment]
Note: Hold off on adding DOIs until I get this feature added (shortly, with luck). Side effect of how we manage references prevents the link from retroactively updating, so the old DOIs won't link out even after I make the change (!). There is no easy fix for this, so we will have to "edit" records with DOIs and re-save them (with no changes) to make them show up as links.

**Comment by foozleface** [comment]
Done, check it out. I updated your most recent entry.

**Comment by bpescador** [comment]
Nice!

**Comment by bpescador** [comment]
one issue with DOI's:  they are showing up next to the default ref insert
on the edit pages:

**Comment by foozleface** [comment]
That's no good.

**Comment by bpescador** [comment]
and when it shows up on a taxon page, there is extra code:  see attached.

**Comment by foozleface** [comment]
For some reason, your images aren't showing on github... email me?

**Comment by foozleface** [comment]
done
